name: build
on:
  push:
    tags:
      - 'release-v*'
    branches:
      - master
    paths-ignore:
      - 'publish/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'publish/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: install packages
        run: npm install
      - name: build production app
        run: npm run build:prod
      - name: publish
        if: {{ github.ref == 'ref/tags/release-v*' }}
        run: npm run publish
      - name: commit published
        if: {{ github.ref == 'ref/tags/release-v*' }}
        # https://github.com/marketplace/actions/add-commit
        uses: EndBug/add-and-commit@v4
        with:
          ref: 'publish'
          add: 'publish'
          force: true
          message: '[actions] publish'
          author_name: github action build
          author_email: github-actions@tylertech.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

