name: build
on:
  push:
    tags:
      - 'release-v*'
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: install packages
        run: npm install
      - name: build production app
        run: npm run build:prod
      - name: publish
        if: ${{ github.ref == 'ref/tags/release-v*' }}
        run: |
          git checkout publish
          git config user.name 'github actions build'
          git config user.email 'github-actions@tylertech.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tyler-technologies-oss/codecomp-dropper.git
          git reset --hard master
          npm run publish
          git add docs --force
          git commit -m "[actions] publish"
          git push --force
